services:
  assistant-server:
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REDIS_HOST=${REDIS_HOST}
      - MONGO_HOST=${MONGO_HOST}
    build:
      context: .
    ports:
      - 8080:8080
